### ISSUE TITLE
Voice synthesis failed miserably

### ISSUE THREAD

**Issue by Angusoft-India** [Apress/Practical-Bot-Development#1]
Hi,

I am trying the sample code mentioned in Section 09. When I tried to place a call from Twilio number I am getting the following error. Please help. Thanks

(node:11556) UnhandledPromiseRejectionWarning: Error: Voice synthesis failed miserably: Voice synthesis failed miserably: Wrong status code 401 in Bing Speech API / token
    at synthesizeStream.then.catch (C:\sample\Practical-Bot-Development-master\chapter09-directline-webchat-and-voice-bot\node_modules\bingspeech-api-client\lib\client.js:112:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:11556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id:
1)
(node:11556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by srozga** [comment]
Hi there
A 401 error means that the call was unauthorized. Do you have a valid bing speech API key assigned to your MICROSOFT_BING_SPEECH_KEY env variable in your .env file?
-s

**Comment by srozga** [comment]
I did a bit of research on this. Turns out the Bing Speech API is being deprecated and being replaced by the Speech API. The client libraries are different and the Node JS libraries don't yet support Text to Speech natively, though there's a way to do it via APIs. I'll try to fix this today or tomorrow. Thanks for the heads up.
-s

**Comment by Angusoft-India** [comment]
Thanks a lot Srozga.

**Comment by srozga** [comment]
Ok finally got to it. @IyyappanAmirthalingam Get latest. I changed the sample to use the Speech Service API instead of Bing Speech API. You need to make sure you have a SPEECH API key in your .env file with key: SPEECH_SERVICE_KEY. Let me know if you run into any other issues.
